export interface RegistryItem {
  name: string
  type: "registry:ui" | "registry:block" | "registry:example"
  description?: string
  registryDependencies?: string[]
  dependencies?: string[]
  devDependencies?: string[]
  files: string[]
  category?: string
  subcategory?: string | undefined
  chunks?: Array<{
    name: string
    description?: string
    file: string
  }>
}

export type Registry = RegistryItem[]

// Registry for all UI components
export const registry: Registry = [
  // Hero Components
  {
    name: "hero-minimalism",
    type: "registry:ui",
    registryDependencies: ["button"],
    dependencies: ["framer-motion", "lucide-react"],
    files: ["components/catalog/hero/hero-minimalism.tsx"],
    category: "hero",
    subcategory: undefined,
    chunks: [],
  },
  {
    name: "hero-monochrome-launch",
    type: "registry:ui",
    registryDependencies: ["button"],
    dependencies: ["framer-motion", "lucide-react"],
    files: ["components/catalog/hero/hero-monochrome-launch.tsx"],
    category: "hero",
    subcategory: undefined,
    chunks: [],
  },
  {
    name: "hero-orbit-deck",
    type: "registry:ui",
    registryDependencies: ["button"],
    dependencies: ["framer-motion", "lucide-react"],
    files: ["components/catalog/hero/hero-orbit-deck.tsx"],
    category: "hero",
    subcategory: undefined,
    chunks: [],
  },

  // CTA Components
  {
    name: "cta-horizontal-marquee",
    type: "registry:ui",
    registryDependencies: ["button"],
    dependencies: ["framer-motion", "lucide-react"],
    files: ["components/catalog/cta/cta-with-horizontal-marquee.tsx"],
    category: "cta",
    subcategory: undefined,
    chunks: [],
  },
  {
    name: "cta-vertical-marquee",
    type: "registry:ui",
    registryDependencies: ["button"],
    dependencies: ["framer-motion", "lucide-react"],
    files: ["components/catalog/cta/cta-with-vertical-marquee.tsx"],
    category: "cta",
    subcategory: undefined,
    chunks: [],
  },
  {
    name: "cta-vertical-marquee-left",
    type: "registry:ui",
    registryDependencies: ["button"],
    dependencies: ["framer-motion", "lucide-react"],
    files: ["components/catalog/cta/cta-with-vertical-marquee-left.tsx"],
    category: "cta",
    subcategory: undefined,
    chunks: [],
  },
  {
    name: "hero-marquee-large",
    type: "registry:ui",
    registryDependencies: ["button"],
    dependencies: ["framer-motion", "lucide-react"],
    files: ["components/catalog/cta/hero-with-marquee-large.tsx"],
    category: "cta",
    subcategory: undefined,
    chunks: [],
  },
  {
    name: "hero-marquee-mixed-font",
    type: "registry:ui",
    registryDependencies: ["button"],
    dependencies: ["framer-motion", "lucide-react"],
    files: ["components/catalog/cta/hero-with-marquee-mixed-font.tsx"],
    category: "cta",
    subcategory: undefined,
    chunks: [],
  },
  {
    name: "hero-marquee-reverse",
    type: "registry:ui",
    registryDependencies: ["button"],
    dependencies: ["framer-motion", "lucide-react"],
    files: ["components/catalog/cta/hero-with-marquee-reverse.tsx"],
    category: "cta",
    subcategory: undefined,
    chunks: [],
  },
  {
    name: "hero-marquee",
    type: "registry:ui",
    registryDependencies: ["button"],
    dependencies: ["framer-motion", "lucide-react"],
    files: ["components/catalog/cta/hero-with-marquee.tsx"],
    category: "cta",
    subcategory: undefined,
    chunks: [],
  },
  {
    name: "hero-video",
    type: "registry:ui",
    registryDependencies: ["button"],
    dependencies: ["framer-motion", "lucide-react"],
    files: ["components/catalog/cta/hero-with-video.tsx"],
    category: "cta",
    subcategory: undefined,
    chunks: [],
  },

  // Features Components
  {
    name: "bento-features",
    type: "registry:ui",
    registryDependencies: ["card"],
    dependencies: ["framer-motion", "lucide-react"],
    files: ["components/catalog/features/bento-features.tsx"],
    category: "features",
    subcategory: undefined,
    chunks: [],
  },
  {
    name: "bento-monochrome-1",
    type: "registry:ui",
    registryDependencies: ["card"],
    dependencies: ["framer-motion", "lucide-react"],
    files: ["components/catalog/features/bento-monochrome-1.tsx"],
    category: "features",
    subcategory: undefined,
    chunks: [],
  },
  {
    name: "bento-monochrome",
    type: "registry:ui",
    registryDependencies: ["card"],
    dependencies: ["framer-motion", "lucide-react"],
    files: ["components/catalog/features/bento-monochrome.tsx"],
    category: "features",
    subcategory: undefined,
    chunks: [],
  },

  // FAQ Components
  {
    name: "faq-monochrome",
    type: "registry:ui",
    registryDependencies: [],
    dependencies: ["framer-motion", "lucide-react"],
    files: ["components/catalog/faq/faq-monochrome.tsx"],
    category: "faq",
    subcategory: undefined,
    chunks: [],
  },
  {
    name: "faq-spiral",
    type: "registry:ui",
    registryDependencies: [],
    dependencies: ["framer-motion", "lucide-react"],
    files: ["components/catalog/faq/faq-with-spiral.tsx"],
    category: "faq",
    subcategory: undefined,
    chunks: [],
  },

  // Login/Signup Components
  {
    name: "login-card",
    type: "registry:ui",
    registryDependencies: ["card", "button", "input", "label", "checkbox"],
    dependencies: ["lucide-react"],
    files: ["components/catalog/login-signup/login-card.tsx"],
    category: "login-signup",
    subcategory: undefined,
    chunks: [],
  },

  // Pricing Components
  {
    name: "pricing-cards",
    type: "registry:ui",
    registryDependencies: ["card", "button"],
    dependencies: ["framer-motion", "lucide-react"],
    files: ["components/catalog/pricing/pricing-cards.tsx"],
    category: "pricing",
    subcategory: undefined,
    chunks: [],
  },

  // Processing Components
  {
    name: "processing-demo",
    type: "registry:ui",
    registryDependencies: ["processing-card"],
    dependencies: ["framer-motion"],
    files: ["components/catalog/processing/processing-demo.tsx"],
    category: "processing",
    subcategory: undefined,
    chunks: [],
  },

  // Background Components
  {
    name: "background-gradient-grid",
    type: "registry:ui",
    registryDependencies: [],
    dependencies: [],
    files: ["components/catalog/backgrounds/background-gradient-grid.tsx"],
    category: "backgrounds",
    subcategory: undefined,
    chunks: [],
  },
  {
    name: "background-noise",
    type: "registry:ui",
    registryDependencies: ["noise"],
    dependencies: [],
    files: ["components/catalog/backgrounds/background-noise.tsx"],
    category: "backgrounds",
    subcategory: undefined,
    chunks: [],
  },
  {
    name: "blueprint-gradient-mesh",
    type: "registry:ui",
    registryDependencies: [],
    dependencies: [],
    files: ["components/catalog/backgrounds/blueprint-gradient-mesh.tsx"],
    category: "backgrounds",
    subcategory: undefined,
    chunks: [],
  },
  {
    name: "squares-background",
    type: "registry:ui",
    registryDependencies: [],
    dependencies: [],
    files: ["components/catalog/backgrounds/squares-background.tsx"],
    category: "backgrounds",
    subcategory: undefined,
    chunks: [],
  },

  // Base UI Components
  {
    name: "button",
    type: "registry:ui",
    registryDependencies: [],
    dependencies: ["@radix-ui/react-slot", "class-variance-authority"],
    files: ["components/ui/button.tsx"],
    category: "ui",
    subcategory: undefined,
    chunks: [],
  },
  {
    name: "card",
    type: "registry:ui",
    registryDependencies: [],
    dependencies: [],
    files: ["components/ui/card.tsx"],
    category: "ui",
    subcategory: undefined,
    chunks: [],
  },
  {
    name: "input",
    type: "registry:ui",
    registryDependencies: [],
    dependencies: [],
    files: ["components/ui/input.tsx"],
    category: "ui",
    subcategory: undefined,
    chunks: [],
  },
  {
    name: "label",
    type: "registry:ui",
    registryDependencies: [],
    dependencies: ["@radix-ui/react-label"],
    files: ["components/ui/label.tsx"],
    category: "ui",
    subcategory: undefined,
    chunks: [],
  },
  {
    name: "checkbox",
    type: "registry:ui",
    registryDependencies: [],
    dependencies: ["@radix-ui/react-checkbox", "lucide-react"],
    files: ["components/ui/checkbox.tsx"],
    category: "ui",
    subcategory: undefined,
    chunks: [],
  },
  {
    name: "switch",
    type: "registry:ui",
    registryDependencies: [],
    dependencies: ["@radix-ui/react-switch"],
    files: ["components/ui/switch.tsx"],
    category: "ui",
    subcategory: undefined,
    chunks: [],
  },
  {
    name: "separator",
    type: "registry:ui",
    registryDependencies: [],
    dependencies: ["@radix-ui/react-separator"],
    files: ["components/ui/separator.tsx"],
    category: "ui",
    subcategory: undefined,
    chunks: [],
  },
  {
    name: "noise",
    type: "registry:ui",
    registryDependencies: [],
    dependencies: [],
    files: ["components/ui/noise.tsx"],
    category: "ui",
    subcategory: undefined,
    chunks: [],
  },
  {
    name: "processing-card",
    type: "registry:ui",
    registryDependencies: ["card"],
    dependencies: ["framer-motion"],
    files: ["components/ui/processing-card.tsx"],
    category: "ui",
    subcategory: undefined,
    chunks: [],
  },
  {
    name: "fallback-card",
    type: "registry:ui",
    registryDependencies: ["card"],
    dependencies: [],
    files: ["components/ui/fallback-card.tsx"],
    category: "ui",
    subcategory: undefined,
    chunks: [],
  },
  {
    name: "hyper-text",
    type: "registry:ui",
    registryDependencies: [],
    dependencies: ["framer-motion"],
    files: ["components/ui/hyper-text.tsx"],
    category: "ui",
    subcategory: undefined,
    chunks: [],
  },
]

